version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Stream Taylor Swift's The Man" > my_workspace/echo-output
      - persist_to_workspace: 
          root: my_workspace
          paths:
            - echo-output  
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: cat my_workspace/echo-output
      - store_test_results:
          path: test-results

  testb:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Stream Taylor Swift's The Man" ]]; then
            echo "Doing the Lord's work!";
          else
            echo "Girlie get STREAMING!"; exit 1
          fi 

  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace: 
          at: my_workspace
      - run: | 
          echo "Deploying message!"
          cat my_workspace/echo-output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
          requires:
            - build 
      - testb:
          requires:
            - build 
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - testa
            - testb 