version: 2.1

orbs:
  hello-build: circleci/hello-build@0.0.14

executors:
  node:
    docker: 
      - image: circleci/node:latest
      
jobs:
  build: 
    executor:
      name: node
    steps:
      - run: echo "hello world"

workflows: 
  version: 2.1
  hello_world: 
    jobs: 
      - hello-build/hello-build
  build:
    jobs: 
      - build